export const MAKES = [
  "Toyota",
  "Honda",
  "Ford",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Porsche",
  "Lamborghini",
  "Ferrari",
  "Nissan",
  "Mazda",
  "Subaru",
  "Volkswagen",
  "Hyundai",
  "Kia",
  "Chevrolet",
  "Dodge",
  "Jeep",
  "Tesla",
  "Rivian",
  "Acura",
  "Buick",
  "Cadillac",
  "Chrysler",
  "GMC",
  "Infiniti",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Mini",
  "Mitsubishi",
  "RAM",
  "Volvo",
];

export const START_YEAR = 1900;
export const END_YEAR = new Date().getFullYear() + 1;

export const YEARS = Array.from(
  { length: END_YEAR - START_YEAR + 1 },
  (_, i) => (END_YEAR - i).toString(),
);

export const MODELS: Record<string, string[]> = {
  Acura: [
    "ADX",
    "CL",
    "Cobra",
    "ILX",
    "Integra",
    "Legend",
    "MDX",
    "NSX",
    "RDX",
    "RL",
    "RLX",
    "RSX",
    "SLX",
    "TL",
    "TLX",
    "TSX",
    "TSX Sport Wagon",
    "Vigor",
    "ZDX",
  ],
  Audi: [
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Allroad",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q6 e-tron",
    "Q7",
    "Q8",
    "Q8 e-tron",
    "R8",
    "RS Q8",
    "RS3",
    "RS4",
    "RS5",
    "RS6",
    "RS7",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "SQ5",
    "SQ6 e-tron",
    "SQ7",
    "SQ8",
    "SQ8 e-tron",
    "TT",
    "TT RS",
    "TTS",
    "e-tron",
    "e-tron GT",
    "e-tron S",
  ],
  BMW: [
    "2 Series",
    "3 Series",
    "4 Series",
    "5 Series",
    "6 Series",
    "7 Series",
    "8 Series",
    "M2",
    "M2 CS",
    "M2 Competition",
    "M3",
    "M4",
    "M5",
    "M6",
    "M8",
    "X1",
    "X2",
    "X3",
    "X3 M",
    "X4",
    "X4 M",
    "X5",
    "X5 M",
    "X6",
    "X6 M",
    "X7",
    "XM",
    "Z4",
    "i3",
    "i4",
    "i5",
    "i7",
    "i8",
    "iX",
  ],
  Buick: [
    "Cascada",
    "Enclave",
    "Encore",
    "Encore GX",
    "Envision",
    "Envista",
    "LaCrosse",
    "Regal",
  ],
  Cadillac: [
    "ATS",
    "CT4",
    "CT5",
    "CT6",
    "CTS",
    "Escalade",
    "Escalade IQ",
    "Lyriq",
    "Optiq",
    "Vistiq",
    "XT4",
    "XT5",
    "XT6",
    "XTS",
  ],
  Chevrolet: [
    "Blazer",
    "Blazer EV",
    "Bolt EUV",
    "Bolt EV",
    "BrightDrop",
    "Camaro",
    "City Express",
    "Colorado",
    "Corvette",
    "Cruze",
    "Equinox",
    "Equinox EV",
    "Express",
    "Impala",
    "Malibu",
    "Silverado 1500",
    "Silverado 2500HD",
    "Silverado 3500HD",
    "Silverado EV",
    "Sonic",
    "Spark",
    "Suburban",
    "Tahoe",
    "TrailBlazer",
    "Traverse",
    "Trax",
    "Volt",
  ],
  Chrysler: ["300", "Pacifica", "Voyager"],
  Dodge: [
    "Challenger",
    "Charger",
    "Durango",
    "Grand Caravan",
    "Hornet",
    "Journey",
  ],
  Ford: [
    "Bronco",
    "Bronco Sport",
    "C-Max",
    "E-Transit",
    "EcoSport",
    "Econoline",
    "Edge",
    "Escape",
    "Expedition",
    "Expedition MAX",
    "Explorer",
    "F-150",
    "F-150 Lightning",
    "F-250",
    "F-350",
    "F-450",
    "F-53",
    "F-550",
    "Fiesta",
    "Flex",
    "Focus",
    "Fusion",
    "Maverick",
    "Mustang",
    "Mustang Mach-E",
    "Ranger",
    "Taurus",
    "Transit",
    "Transit Connect",
  ],
  GMC: [
    "Acadia",
    "Canyon",
    "Hummer EV",
    "Savana",
    "Sierra 1500",
    "Sierra 2500HD",
    "Sierra 3500HD",
    "Sierra EV",
    "Terrain",
    "Yukon",
    "Yukon XL",
  ],
  Honda: [
    "Accord",
    "CR-V",
    "Civic",
    "Clarity",
    "Fit",
    "HR-V",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Prologue",
    "Ridgeline",
  ],
  Hyundai: [
    "Accent",
    "Elantra",
    "Elantra N",
    "Ioniq",
    "Ioniq 5",
    "Ioniq 6",
    "Kona",
    "Kona N",
    "Nexo",
    "Palisade",
    "Santa Cruz",
    "Santa Fe",
    "Santa Fe Sport",
    "Santa Fe XL",
    "Sonata",
    "Tucson",
    "Veloster",
    "Veloster N",
    "Venue",
  ],
  Infiniti: ["Q50", "Q60", "Q70", "QX30", "QX50", "QX55", "QX60", "QX80"],
  Jeep: [
    "Cherokee",
    "Compass",
    "Gladiator",
    "Grand Cherokee",
    "Grand Cherokee L",
    "Grand Wagoner",
    "Renegade",
    "Wagoner",
    "Wrangler",
  ],
  Kia: [
    "Cadenza",
    "Carnival",
    "EV6",
    "EV9",
    "Forte",
    "Forte5",
    "K4",
    "K5",
    "K900",
    "Niro",
    "Niro EV",
    "Optima",
    "Rio",
    "Sedona",
    "Seltos",
    "Sorento",
    "Soul",
    "Soul EV",
    "Sportage",
    "Stinger",
    "Telluride",
  ],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
  ],
  Lexus: [
    "ES",
    "GS",
    "GX",
    "IS",
    "LC",
    "LS",
    "LX",
    "NX",
    "RC",
    "RX",
    "RZ",
    "TX",
    "UX",
  ],
  Lincoln: [
    "Aviator",
    "Continental",
    "Corsair",
    "MKC",
    "MKT",
    "MKX",
    "MKZ",
    "Nautilus",
    "Navigator",
    "Navigator L",
  ],
  Mazda: [
    "CX-3",
    "CX-30",
    "CX-5",
    "CX-50",
    "CX-70",
    "CX-9",
    "CX-90",
    "MX-30",
    "Mazda3",
    "Mazda6",
    "Miata",
  ],
  "Mercedes-Benz": [
    "A-Class",
    "AMG GT",
    "C-Class",
    "CLA",
    "CLE",
    "CLS",
    "E-Class",
    "EQB",
    "EQE",
    "EQS",
    "G-Class",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "Metris",
    "S-Class",
    "SL-Class",
    "SLC",
    "Sprinter",
    "eSprinter",
  ],
  Mini: ["Cooper", "Cooper Clubman", "Cooper Countryman"],
  Mitsubishi: [
    "Eclipse Cross",
    "Mirage",
    "Mirage G4",
    "Outlander",
    "Outlander Sport",
  ],
  Nissan: [
    "Altima",
    "Ariya",
    "Armada",
    "Frontier",
    "GT-R",
    "Kicks",
    "Leaf",
    "Maxima",
    "Murano",
    "NV",
    "NV200",
    "Pathfinder",
    "Rogue",
    "Rogue Sport",
    "Sentra",
    "Titan",
    "Titan XD",
    "Versa",
    "Versa Note",
  ],
  Porsche: [
    "718 Boxster",
    "718 Cayman",
    "718 Spyder",
    "911",
    "Boxster",
    "Cayenne",
    "Cayman",
    "Macan",
    "Panamera",
    "Taycan",
  ],
  RAM: [
    "1500",
    "2500",
    "3500",
    "4500",
    "5500",
    "ProMaster",
    "ProMaster City",
    "ProMaster EV",
  ],
  Subaru: [
    "Ascent",
    "BRZ",
    "Crosstrek",
    "Forester",
    "Impreza",
    "Legacy",
    "Outback",
    "STI S209",
    "Solterra",
    "WRX",
  ],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
  Toyota: [
    "4Runner",
    "86",
    "Avalon",
    "C-HR",
    "Camry",
    "Corolla",
    "Corolla Cross",
    "Corolla iM",
    "Crown",
    "Crown Signia",
    "GR Corolla",
    "GR Supra",
    "GR86",
    "Grand Highlander",
    "Highlander",
    "Land Cruiser",
    "Mirai",
    "Prius",
    "Prius Prime",
    "Prius c",
    "RAV4",
    "Sequoia",
    "Sienna",
    "Supra",
    "Tacoma",
    "Tundra",
    "Venza",
    "Yaris",
    "Yaris iA",
    "bZ4X",
  ],
  Volkswagen: [
    "Arteon",
    "Atlas",
    "Beetle",
    "Golf",
    "ID.4",
    "ID.Buzz",
    "Jetta",
    "Passat",
    "Taos",
    "Tiguan",
    "Transporter",
    "e-Golf",
  ],
  Volvo: [
    "C40",
    "EC40",
    "EX30",
    "EX40",
    "EX90",
    "S60",
    "S90",
    "V60",
    "V90",
    "XC40",
    "XC60",
    "XC90",
  ],
  Rivian: ["R1T", "R1S", "R2", "R3"],
  Ferrari: ["296", "812", "F8", "Roma", "SF90", "Purosangue"],
  Lamborghini: ["Aventador", "Huracan", "Revuelto", "Urus"],
};
