import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { TopNav } from "../components/layout/top-nav";
import { Toaster } from "@/components/ui/sonner";
import { getUserCars } from "@/app/actions/cars";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "yearmnm",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch session
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  // If logged in, fetch favorites. Otherwise empty.
  const favorites = session ? await getUserCars(session.user.id) : [];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense>
          <TopNav favorites={favorites} session={session} />
        </Suspense>
        {children}
        <Suspense>
          <Toaster />
        </Suspense>
      </body>
    </html>
  );
}
